#- platform: ps4
#  host: 192.168.0.197

- platform: samsungtv
  host: 192.168.0.10
  port: 8001

- platform: kodi
  host: 192.168.0.11
  turn_on_action:
    - service: wake_on_lan.send_magic_packet
      data:
        mac: !secret kodi_mac
  turn_off_action:
    - service: media_player.kodi_call_method
      data:
        entity_id: media_player.kodi
        method: System.Shutdown
