#- platform: yr
#- platform: fritzbox_netmonitor
#  host: 192.168.0.254
- platform: pi_hole
  host: 192.168.0.250

- platform: template
  sensors:
    wc_heizung_stromverbrauch:
      value_template: "{{ state_attr('switch.schalter_wc_heizung', 'current_power_w') | float }}"
      unit_of_measurement: 'W'
      friendly_name: 'WC Heizung Stromverbrauch'

    wc_heizung_gesamt_stromverbrauch:
      value_template: "{{ state_attr('switch.schalter_wc_heizung', 'total_consumption') }}"
      unit_of_measurement: 'kWh'
      friendly_name: 'WC Heizung Gesamt Stromverbrauch'

    trockner_stromverbrauch:
      value_template: "{{ state_attr('switch.keller_trockner', 'current_power_w') | float }}"
      unit_of_measurement: 'W'
      friendly_name: 'Trockner Stromverbrauch'

    trockner_gesamt_stromverbrauch:
      value_template: "{{ state_attr('switch.keller_trockner', 'total_consumption') }}"
      unit_of_measurement: 'kWh'
      friendly_name: 'Trockner Gesamt Stromverbrauch'

    status_trockner:
        friendly_name: 'Trockner'
        value_template: >-
          {% if states('sensor.trockner_stromverbrauch')|float <= 0 %}
            Aus
          {% elif states('sensor.trockner_stromverbrauch')|float < 100 %}
            Fertig
          {% elif states('sensor.trockner_stromverbrauch')|float >= 100 %}
            Trocknet
          {% else %}
            PRÜFEN!
          {% endif %}
