- platform: yr
- platform: lacrosse
  sensors:
    aussen_temperature:
      name: Aussen Temperatur
      type: temperature
      id: 200
    aussen_lacrosse_battery:
      name: Aussen Sensor Batterie
      type: battery
      id: 200

    wc_humidity:
      name: WC Luftfeuchtigkeit
      type: humidity
      id: 128
    wc_temperature:
      name: WC Temperatur
      type: temperature
      id: 128
    wc_lacrosse_battery:
      name: WC Sensor Batterie
      type: battery
      id: 128

    abstellraum_humidity:
      name: Abstellraum Luftfeuchtigkeit
      type: humidity
      id: 112
    abstellraum_temperature:
      name: Abstellraum Temperatur
      type: temperature
      id: 112
    abstellraum_lacrosse_battery:
      name: Abstellraum Sensor Batterie
      type: battery
      id: 112

    wohnzimmer_humidity:
      name: Wohnzimmer Luftfeuchtigkeit
      type: humidity
      id: 72
    wohnzimmer_temperature:
      name: Wohnzimmer Temperatur
      type: temperature
      id: 72
    wohnzimmer_lacrosse_battery:
      name: Wohnzimmer Sensor Batterie
      type: battery
      id: 72

    keller_humidity:
      name: Keller Luftfeuchtigkeit
      type: humidity
      id: 0
    keller_temperature:
      name: Keller Temperatur
      type: temperature
      id: 0
    keller_lacrosse_battery:
      name: Keller Sensor Batterie
      type: battery
      id: 0

    badezimmer_humidity:
      name: Badezimmer Luftfeuchtigkeit
      type: humidity
      id: 152
    badezimmer_temperature:
      name: Badezimmer Temperatur
      type: temperature
      id: 152
    badezimmer_lacrosse_battery:
      name: Badezimmer Sensor Batterie
      type: battery
      id: 152

    paulina_humidity:
      name: Paulina Luftfeuchtigkeit
      type: humidity
      id: 16
    paulina_temperature:
      name: Paulina Temperatur
      type: temperature
      id: 16
    paulina_lacrosse_battery:
      name: Paulina Sensor Batterie
      type: battery
      id: 16

    marie_humidity:
      name: Marie Luftfeuchtigkeit
      type: humidity
      id: 144
    marie_temperature:
      name: Marie Temperatur
      type: temperature
      id: 144
    marie_lacrosse_battery:
      name: Marie Sensor Batterie
      type: battery
      id: 144

    jakob_humidity:
      name: Jakob Luftfeuchtigkeit
      type: humidity
      id: 216
    jakob_temperature:
      name: Jakob Temperatur
      type: temperature
      id: 216
    jakob_lacrosse_battery:
      name: Jakob Sensor Batterie
      type: battery
      id: 216

    schlafzimmer_humidity:
      name: Schlafzimmer Luftfeuchtigkeit
      type: humidity
      id: 40
    schlafzimmer_temperature:
      name: Schlafzimmer Temperatur
      type: temperature
      id: 40
    schlafzimmer_lacrosse_battery:
      name: Schlafzimmer Sensor Batterie
      type: battery
      id: 40
