- platform: mqtt
  name: "Sonoff power 1"
  state_topic: "stat/sonoff-1/POWER"
  command_topic: "cmnd/sonoff-1/POWER"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  retain: true

- platform: mqtt
  name: "Sonoff power 2"
  state_topic: "stat/sonoff-2/POWER"
  command_topic: "cmnd/sonoff-2/POWER"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  retain: true
