- alias: Switch nicht erreichbar
  trigger:
    - platform: state
      entity_id: switch.wc_heizung
      to: unavailable
  action:
    - service: notify.telegram
      data:
        message: "Switch WC Heizung nicht mehr verbunden."

##
## Thermostate Überwachung
##
- alias: Thermostate in Paulina's Zimmer nicht erreichbar
  trigger:
    - platform: state
      entity_id: climate.paulina
      to: unavailable
  action:
    - service: notify.telegram
      data:
        message: "Thermostate in Paulina's Zimmer nicht mehr verbunden."

- alias: Thermostate in Marie's Zimmer nicht erreichbar
  trigger:
    - platform: state
      entity_id: climatem.marie
      to: unavailable
  action:
    - service: notify.telegram
      data:
        message: "Thermostate in Marie's Zimmer nicht mehr verbunden."

- alias: Thermostate in Jakob's Zimmer nicht erreichbar
  trigger:
    - platform: state
      entity_id: climatem.jakob
      to: unavailable
  action:
    - service: notify.telegram
      data:
        message: "Thermostate in Jakob's Zimmer nicht mehr verbunden."

- alias: Thermostate im Badezimmer nicht erreichbar
  trigger:
    - platform: state
      entity_id: climatem.badezimmer
      to: unavailable
  action:
    - service: notify.telegram
      data:
        message: "Thermostate im Badezimmer nicht mehr verbunden."
