- alias: Temperaturüberwachung Wohnzimmer
  trigger:
    - platform: numeric_state
      entity_id: sensor.wohnzimmer_temperature
      below: 18
  action:
    - service: notify.telegram
      data:
        message: "Temperatur im Wohnzimmer ist unter 18 Grad."

- alias: Switch nicht erreichbar
  trigger:
    - platform: state
      entity_id: switch.wc_heizung
      to: unavailable
  action:
    - service: notify.telegram
      data:
        message: "Switch WC Heizung nicht mehr verbunden."


